### ISSUE TITLE
Automagically display past and future streams

### ISSUE THREAD

**Issue by raae** [raae/nattermob.dev#6]
Wouldn't it be nice if the site updated itself based on data already existing on YouTube without us having to manually copy that to some sort of Content Management System?

**Comment by PaulieScanlon** [comment]
Yeap. I think once we've done this weeks stream and added the YouTube API stuff i think we could do a GitHub action to rebuild and re-deploy once a week or more.... To the best of my knowledge there's no webhook unless you pay for a special Google key.

**Comment by raae** [comment]
First we sourced the streams into the @GatsbyJS content system from YouTube via the YouTube API 📺

https://youtu.be/tJHV96jVlKg

**Comment by raae** [comment]
Second we created pages for each sourced video using the @GatsbyJS File System Route API. 

Bonus Pirate: @wardpeet, Gatsby Tech Lead 

https://youtu.be/TX5XPuHhz9o

**Comment by raae** [comment]
Tonight we'll make an index page+++

https://youtu.be/X_3VD8t215o
